---
## Note
# Do not use chars other than [a-zA-Z0-9._-] for usernames
# prosody likes to encode chars other than alphanumerics in files/dirs names

## Videobridge XMPP credetials
videobridge_user: jvb_CHANGEME
videobridge_pass: "{{ vault_videobridge_pass }}"
# Set this to something different that "videobridge_user" if you want to share
# videobridge_user and videobridge_pass across different videobridges
videobridge_muc_nick: jvb_CHANGEME
